version: '3'

networks:
  gunicorn_net:

services:
  app1:
    build: .
    networks:
      - gunicorn_net
    restart: always
    # ports:
    #   - 8000:8000
  app2:
    build: .
    networks:
      - gunicorn_net
    restart: always
    # ports:
    #   - 8001:8000
  web:
    image: nginx:latest
    networks:
      - gunicorn_net
    ports:
      - 80:80
    volumes:
      - "./nginx.conf:/etc/nginx/conf.d/default.conf"
